#!/usr/bin/env python3
import sys
import os

_BASE = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(_BASE, "src", "vendor"))
sys.path.insert(0, os.path.join(_BASE, "src"))

from cli import main
main()
