[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "pipbot"
version = "0.1.0"
description = "A framework for building modular robotics software on Raspberry Pi"
requires-python = ">=3.9"
dependencies = ["pyyaml"]

[project.scripts]
bot = "pipbot.cli:main"
